ALL:
	make -C ./bin

clean:
	rm -rf CUMC3D
	rm -rf ./bin/*.o
	rm -rf ./bin/*.mod
	rm tmp.txt
cleanpic:
	rm -rf ./plot/*.png
	rm -rf ./plot/*.mp4
cleanfile:
	rm -rf ./outfile/*.dat
	rm -rf ./outfile/*.hdf5
